default/generated/cloud-readiness/07-local-storage.windup.yaml
This should make it so CI can go green while we work to address the root cause.
=> :bug: Manually revert rule added by windup-shim

default/generated/technology-usage/188-3rd-party.windup.yaml, default/generated/technology-usage/192-configuration-management.windup.yaml, default/generated/technology-usage/194-connect.windup.yaml, default/generated/technology-usage/196-database.windup.yaml, default/generated/technology-usage/199-ejb.windup.yaml, default/generated/technology-usage/201-embedded-framework.windup.yaml, default/generated/technology-usage/204-integration.windup.yaml, default/generated/technology-usage/207-javase.windup.yaml, default/generated/technology-usage/209-jta.windup.yaml, default/generated/technology-usage/21-javaee-technology-usage.windup.yaml, default/generated/technology-usage/211-logging-usage.windup.yaml, default/generated/technology-usage/215-mvc.windup.yaml, default/generated/technology-usage/218-observability.windup.yaml, default/generated/technology-usage/220-security.windup.yaml, default/generated/technology-usage/221-spring-catchall.windup.yaml, default/generated/technology-usage/223-test-frameworks-usage.windup.yaml, default/generated/technology-usage/33-connect-technology-usage.windup.yaml
Fixes https://github.com/konveyor/rulesets/issues/55
=> :bug: Remove message from technology-usage rules so that they don't appear as issues, only as tags

default/generated/technology-usage/188-3rd-party.windup.yaml, default/generated/technology-usage/192-configuration-management.windup.yaml, default/generated/technology-usage/194-connect.windup.yaml, default/generated/technology-usage/196-database.windup.yaml, default/generated/technology-usage/199-ejb.windup.yaml, default/generated/technology-usage/201-embedded-framework.windup.yaml, default/generated/technology-usage/204-integration.windup.yaml, default/generated/technology-usage/207-javase.windup.yaml, default/generated/technology-usage/209-jta.windup.yaml, default/generated/technology-usage/21-javaee-technology-usage.windup.yaml, default/generated/technology-usage/211-logging-usage.windup.yaml, default/generated/technology-usage/215-mvc.windup.yaml, default/generated/technology-usage/218-observability.windup.yaml, default/generated/technology-usage/220-security.windup.yaml, default/generated/technology-usage/221-spring-catchall.windup.yaml, default/generated/technology-usage/223-test-frameworks-usage.windup.yaml, default/generated/technology-usage/33-connect-technology-usage.windup.yaml
Signed-off-by: Juan Manuel Leflet Estrada <jleflete@redhat.com>
(cherry picked from commit 66865bab2db2f61734db1b7bc5ae8e2dcd7045e0)
=> Remove message from technology-usage rules so that they don't appear as issues, only as tags (#56)

.github/workflows/global-ci.yaml, default/generated/camel3/18-java-generic-information.windup.yaml, default/generated/technology-usage/204-integration.windup.yaml
Cherry picked from 871ce5c1cbc5741fc690e2c9f5423e0891e63a95
=> :bug: Fix bad yaml file (#58)

default/generated/eap6/31-xml-webservices.windup.yaml, default/generated/eap6/55-weblogic-xml-descriptors.windup.yaml, default/generated/eap7/82-hibernate51-53.windup.yaml, default/generated/eap7/98-weblogic-xml-descriptors.windup.yaml, default/generated/eap8/120-javaee-to-jakarta-namespaces.windup.yaml, default/generated/hibernate/143-hibernate-xml.windup.yaml
=> :bug: improve accuracy on chained builtin conditions

default/generated/azure/04-azure-logging.windup.yaml, default/generated/azure/07-eap-to-azure-appservice-certificates.windup.yaml, default/generated/azure/12-spring-boot-to-azure-config-server.windup.yaml, default/generated/azure/14-spring-boot-to-azure-eureka.windup.yaml, default/generated/azure/20-spring-boot-to-azure-mq-config.windup.yaml, default/generated/cloud-readiness/01-embedded-cache-libraries.windup.yaml, default/generated/cloud-readiness/03-java-rmi.windup.yaml, default/generated/cloud-readiness/155-embedded-cache-libraries.windup.yaml, default/generated/cloud-readiness/156-java-rmi.windup.yaml, default/generated/eap6/27-xml-glassfish.windup.yaml, default/generated/eap6/28-java-ee-jaxrpc.windup.yaml, default/generated/eap6/31-xml-webservices.windup.yaml, default/generated/eap6/34-jboss-eap5-xml.windup.yaml, default/generated/eap6/39-xml-jrun.windup.yaml, default/generated/eap6/55-weblogic-xml-descriptors.windup.yaml, default/generated/eap6/61-websphere-mqe.windup.yaml, default/generated/eap7/100-websphere-jms.windup.yaml, default/generated/eap7/101-websphere-mq.windup.yaml, default/generated/eap7/102-websphere-mqe.windup.yaml, default/generated/eap7/104-websphere-xml.windup.yaml
Cherry-picked from 6637c8ebf07edfadb0ed793ab5249131397b02d7
=> Remove messages from tagging rules with no effort (#64)

default/generated/azure/08-eap-to-azure-appservice-datasource-driver.windup.yaml, default/generated/camel3/18-java-generic-information.windup.yaml, default/generated/cloud-readiness/04-java-rpc.windup.yaml, default/generated/cloud-readiness/157-java-rpc.windup.yaml, default/generated/eap6/32-eap4-xml-config.windup.yaml, default/generated/eap6/34-jboss-eap5-xml.windup.yaml, default/generated/eap6/45-generic-catchall.windup.yaml, default/generated/eap6/62-websphere-other.windup.yaml, default/generated/eap7/103-websphere-other.windup.yaml, default/generated/eap7/104-websphere-xml.windup.yaml, default/generated/eap7/71-jboss-eap5and6to7-xml.windup.yaml, default/generated/eap7/73-eap6-xml.windup.yaml, default/generated/eap7/75-hibernate4-xml.windup.yaml, default/generated/eap8/112-hibernate-search.windup.yaml, default/generated/eap8/113-hibernate6.windup.yaml, default/generated/hibernate/142-hibernate-catchall.windup.yaml, default/generated/technology-usage/07-security-technology-usage.windup.yaml, default/generated/technology-usage/21-javaee-technology-usage.windup.yaml
This also fixes duplicate As fields wherever required
=> :bug: fix wildcards in the middle of the pattern string

default/generated/quarkus/200-ee-to-quarkus.windup.yaml, default/generated/quarkus/201-persistence-to-quarkus.windup.yaml, default/generated/quarkus/202-remote-ejb-to-quarkus.windup.yaml, default/generated/quarkus/210-cdi-to-quarkus.windup.yaml
https://github.com/konveyor/rulesets/issues/47
=> Add some new JavaEE to Quarkus rules

.gitignore, default/generated/eap8/162-javax-to-jakarta-bootstrapping-files.windup.yaml, default/generated/eap8/163-javax-to-jakarta-dependencies.windup.yaml, default/generated/eap8/164-javax-to-jakarta-package.windup.yaml, default/generated/eap8/165-javax-to-jakarta-properties.windup.yaml, default/generated/eap8/166-javax-to-jakarta-servlet.windup.yaml, default/generated/openjdk17/193-applet-api-deprecation.windup.yaml, default/generated/openjdk17/194-lombok.windup.yaml, default/generated/openjdk17/195-removed-classes.windup.yaml, default/generated/openjdk17/196-removed-packages.windup.yaml, default/generated/openjdk17/197-security-manager-deprecation.windup.yaml, default/generated/spring-framework/ruleset.yaml, default/generated/spring-framework/spring-framework-5.x-to-6.0-baseline.yaml, default/generated/spring-framework/tests/data/pom.xml, default/generated/spring-framework/tests/spring-framework-5.x-to-6.0-baseline.test.yaml
Fixes issue https://github.com/konveyor/rulesets/issues/133
=> Create rule for baseline requirements for migrating Spring Framework 5.x to 6.0

default/generated/spring-framework/spring-framework-5.x-to-6.0-data-access.yaml, default/generated/spring-framework/tests/data/data-access/pom.xml, default/generated/spring-framework/tests/spring-framework-5.x-to-6.0-data-access.test.yaml
See https://github.com/konveyor/rulesets/issues/143
=> :sparkles: Rule for hibernate upgrade

.gitignore, default/generated/spring-framework/spring-framework-5.x-to-6.0-web-applications.yaml, default/generated/spring-framework/tests/data/web-applications/pom.xml, default/generated/spring-framework/tests/data/web-applications/src/main/java/org/konveyor/Main.java, default/generated/spring-framework/tests/data/web-applications/src/main/java/org/konveyor/controller/Controller.java, default/generated/spring-framework/tests/spring-framework-5.x-to-6.0-web-applications.test.yaml
See https://github.com/konveyor/rulesets/issues/151
=> :sparkles: Add trailing slash in GetMapping rule

default/generated/spring-framework/spring-framework-5.x-to-6.0-data-access.yaml, default/generated/spring-framework/tests/data/data-access/pom.xml, default/generated/spring-framework/tests/spring-framework-5.x-to-6.0-data-access.test.yaml
https://github.com/konveyor/rulesets/issues/145
=> Add EclipseLink rules

default/generated/spring-framework/spring-framework-5.x-to-6.0-core-container.yaml, default/generated/spring-framework/tests/data/core-container/src/main/java/org/konveyor/spel/DynamicQueryService.java, default/generated/spring-framework/tests/data/core-container/src/main/java/org/konveyor/spel/SecondaryQueryService.java, default/generated/spring-framework/tests/spring-framework-5.x-to-6.0-core-container.test.yaml
Create rules for SimpleEvaluationContext #142
=> Create rules for SimpleEvaluationContext

default/generated/quarkus/218-jms-to-reactive-quarkus.windup.yaml
The Emitter is not from Micrometer but MicroProfile.
=> Change text: micrometer to MicroProfile

default/generated/spring-framework/spring-framework-5.x-to-6.0-data-access.yaml, default/generated/spring-framework/tests/data/data-access/src/main/resources/sql-error-codes.xml, default/generated/spring-framework/tests/spring-framework-5.x-to-6.0-data-access.test.yaml
Searches for the existence of `sql-error-codes.xml` and reports accordingly
=> Create rules for backwards compatibility with database-specific error codes

default/generated/eap7/120-maven-artemis-jms-client.rhamt.yaml, default/generated/eap8/145-eap8-faces.windup.yaml, default/generated/eap8/152-hibernate-search-6.1.windup.yaml, default/generated/eap8/170-log4j-removed.windup.yaml, default/generated/quarkus/236-springboot-web-to-quarkus.windup.yaml
See https://github.com/konveyor/rulesets/issues/270
=> Fix badly translated rules with and/or

default/generated/spring-boot/spring-boot-2.x-to-3.0-removals.yaml
resolves `error="duplicated rule id: spring-boot-2.x-to-3.0-removals-00010\`
=> Remove duplicate rule IDs

default/generated/camel3/30-component-changes.groovy.windup.yaml, default/generated/eap6/95-environment-dependent.windup.yaml, default/generated/eap7/110-hibernate4.windup.yaml, default/generated/technology-usage/22-javaee-technology-usage.windup.yaml
=> :bug: Fixes in rules

default/generated/camel3/30-component-changes.groovy.windup.yaml, default/generated/eap6/95-environment-dependent.windup.yaml, default/generated/eap7/110-hibernate4.windup.yaml, default/generated/technology-usage/22-javaee-technology-usage.windup.yaml
=> :bug: bug fixes in rules (#280)

default/generated/eap8/161-javaee-to-jakarta-namespaces.windup.yaml
See https://issues.redhat.com/browse/MTA-4025
Requires https://github.com/konveyor/go-konveyor-tests/pull/275 to fix the tests
(Marek updated below)
API tests PR: 275
=> [MTA-4025] Ignore XML side of the rule

default/generated/openjdk21/ruleset.yaml
Fix ruleset title, fixes: https://issues.redhat.com/browse/MTA-4972
Note, checked other rulesets with script too, other titles look okay.
=> Fix openjdk21 ruleset title MTA-4972
